"""Add is_encrypted field to Message model

Revision ID: 42a653bd3989
Revises: ddc5e8548ee6
Create Date: 2025-05-27 13:12:35.241170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a653bd3989'
down_revision = 'ddc5e8548ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
