"""Add encryption fields to Message model

Revision ID: 9a843d3a59bc
Revises: 
Create Date: 2025-05-27 12:04:32.522802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a843d3a59bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('message_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encryption_metadata', sa.Text(), nullable=True))
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('encryption_metadata')
        batch_op.drop_column('message_number')
        batch_op.drop_column('encrypted_content')

    # ### end Alembic commands ###
