"""Add status field to Message model

Revision ID: ddc5e8548ee6
Revises: 9a843d3a59bc
Create Date: 2025-05-27 13:10:42.075657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc5e8548ee6'
down_revision = '9a843d3a59bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
